language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-stable
  - Pharo-6.1
  - Moose-6.1
  - Pharo64-7.0
  - Moose64-7.0
  - Pharo64-8.0
  - Moose64-8.0

smalltalk_config:
  - .core.ston
  - .pp2.ston
  - .languages.ston
  - .gui.ston
# - .rewrite.ston
# - .experimental.ston

matrix:
  allow_failures:
   - smalltalk: Pharo-alpha
